openapi: 3.0.0
info:
  version: 1.0.0
  title: Zuri Chat Core API (Market Place Endpoints)
  description: Zuri Chat is an open source slack clone. However, it offers a lot more functionality via a plugin system where each room can be provided by a different plugin provider.
  contact:
    email: developer@zuri.chat
servers:
  - description: Zuri Chat Core API
    url: 'https://api.zuri.chat/'

paths:
  /marketplace/plugins:
    get:
      tags:
        - marketplace
      summary: Returns a list of plugins on the marketplace
      responses:
        '200':
          description: List of all Plugins
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MarketplacePlugin'
        '404':
          description: Plugins not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /marketplace/plugins/{id}:
    get:
      tags:
        - marketplace
      summary: Get a single marketplace plugin details
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Plugin Approval Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketplacePlugin'

        '403':
          description: Plugin not approved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Plugin not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      tags:
        - Marketplace
      summary: Removes a single plugin from the marketplace.
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Plugin Successfully Removed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketplacePlugin'

        '400':
          description: Plugin does not exist or plugin removal failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Plugin not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    MarketplacePlugin:
      type: object
      properties:
        _id:
          type: string
          example: '6137d69b21d3c78fc9a84bdf'
        name:
          type: string
          example: 'Google Drive'
        description:
          type: string
        developerName:
          type: string
        developerEmail:
          type: string
          example: developer@zuri.chat
        metadata:
          type: object
        templateUrl:
          type: string
        sidebarUrl:
          type: string
        iconUrl:
          type: string
        approved:
          type: boolean
