openapi: 3.0.0
info:
  version: 1.0.0
  title: Zuri Chat Core API (Plugin Endpoints)
  description: Zuri Chat is an open source slack clone. However, it offers a lot more functionality via a plugin system where each room can be provided by a different plugin provider.
  contact:
    email: developer@zuri.chat
servers:
  - description: Zuri Chat Core API
    url: 'https://api.zuri.chat/'

tags:
  - name: plugins
paths:
  /plugins/register:
    post:
      tags:
        - plugin
      security:
        - bearerAuth: []
      description: Register a new plugin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Plugin'
        required: true
      responses:
        '200':
          description: Plugin successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PluginRegistrationResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

        '400':
          $ref: '#/components/responses/BadRequest'

        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
      content:
        application/json:
          schema:
            required:
              - code
              - message
            type: object
            properties:
              code:
                type: integer
                format: int32
                example: 401
              message:
                type: string

    InternalServerError:
      description: Internal server error occured during operation
      content:
        application/json:
          schema:
            required:
              - code
              - message
            type: object
            properties:
              code:
                type: integer
                format: int32
                example: 500
              message:
                type: string

    BadRequest:
      description: Bad Request, e.g missing developer email
      content:
        application/json:
          schema:
            required:
              - code
              - message
            type: object
            properties:
              code:
                type: integer
                format: int32
                example: 400
              message:
                type: string

  schemas:
    Plugin:
      required:
        - name
        - description
        - developer_name
        - developer_email
        - template_url
        - sidebar_url
        - install_url
      type: object
      properties:
        name:
          type: string
          example: 'MyPlugin'
        description:
          type: string
          example: 'This is my plugin'
        developer_name:
          type: string
          example: 'Jane Doe'
        developer_email:
          type: string
          example: 'janedoe@mail.com'
        template_url:
          type: string
          example: 'plugin.zuri.chat/myplugin'
        sidebar_url:
          type: string
          example: 'plugin.zuri.chat/mysidebar'
        install_url:
          type: string
          example: 'plugin.zuri.chat/install'

    PluginRegistrationResponse:
      type: object
      properties:
        status:
          type: integer
          example: 200
        message:
          type: string
          example: 'success'
        data:
          type: object
          properties:
            plugin_id:
              type: string
              example: '6138cd01dbe109094d59ffaa'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
