// eslint-disable-next-line
const Language = [
  " Albanian-shqip",
  " Amharic - አማርኛ ",
  " Arabic - العربية",
  " Aragonese - aragonés",
  " Armenian - հայերեն",
  "Asturian - asturian",
  " Azerbaijani - azərbaycan dili",
  "Basque - euskara",
  " Belarusian - беларуская",
  " Bengali - বাংলা",
  " Bosnian - bosanski",
  " Breton - brezhoneg",
  " Bulgarian - български",
  "Catalan - català",
  "Central Kurdish - کوردی (دەستنوسی عەرەبی)",
  " Chinese - 中文",
  "zhChinese (Hong Kong) - 中文（香港）",
  "zhChinese (Simplified) - 中文（简体）",
  "zhChinese (Traditional) - 中文（繁體）",
  "Corsican",
  "Croatian - hrvatski",
  "Czech - čeština",
  "Danish - dansk",
  "utch - Nederlands",
  "English",
  "enEnglish (Australia)",
  "enEnglish (Canada)",
  "enEnglish (India)",
  "enEnglish (New Zealand)",
  "enEnglish (South Africa)",
  "enEnglish (United Kingdom)",
  "enEnglish (United States)",
  "Esperanto - esperanto",
  " Estonian - eesti",
  "Faroese - føroyskt",
  "Filipin",
  " Finnish - suomi",
  " French - français",
  "frFrench (Canada) - français (Canada)",
  "frFrench (France) - français (France)",
  "French (Switzerland) - français (Suisse)",

  " Galician - galego",
  " Georgian - ქართული",
  "German - Deutsch",
  " German (Austria) - Deutsch (Österreich)",

  "German (Germany) - Deutsch (Deutschland)",

  "German (Liechtenstein) - Deutsch (Liechtenstein)",

  " German (Switzerland) - Deutsch (Schweiz)",

  "Greek - Ελληνικά",
  " Guarani",
  "Gujarati - ગુજરાતી",
  " Hausa",
  "Hawaiian - ʻŌlelo Hawaiʻi",
  " Hebrew - עברית",
  " Hungarian - magyar",
  "Icelandic - íslenska",
  " Indonesian - Indonesia",
  "Interlingua",
  "Irish - Gaeilge",
  "Italian - italiano",
  "itItalian (Italy) - italiano (Italia)",
  ,
  "Italian (Switzerland) - italiano (Svizzera)",

  "Japanese - 日本語",
  " Kannada - ಕನ್ನಡ",
  "Kazakh - қазақ тілі",
  "Khmer - ខ្មែរ",
  " Korean - 한국어",
  "Kurdish - Kurdî",
  " Kyrgyz - кыргызча",
  "Lao - ລາວ",
  " Latin",
  "Latvian - latviešu",
  "Lingala - lingála",
  " Lithuanian - lietuvių",
  "Macedonian - македонски",
  "Malay - Bahasa Melayu",
  " Malayalam - മലയാളം",
  "Maltese - Malti",
  " Marathi - मराठी",
  " Mongolian - монгол",
  "Nepali - नेपाली",
  " Norwegian - norsk",
  "Norwegian Bokmål - norsk bokmål",
  " Norwegian Nynorsk - nynorsk",
  "  Occitan",
  "Oriya - ଓଡ଼ିଆ",
  " Oromo - Oromoo",
  " Pashto - پښتو",
  " Persian - فارسی",
  " Polish - polski",
  " Portuguese - português",

  "Portuguese (Brazil) - português (Brasil)",

  "Portuguese (Portugal) - português (Portugal)",

  "Punjabi - ਪੰਜਾਬੀ",
  " Quechua",
  "Romanian - română",
  "Romanian (Moldova) - română (Moldova)",
  "Romansh - rumantsch",
  "Russian - русский",
  "Scottish Gaelic",
  "Serbian - српски",
  " Serbo-Croatian - Srpskohrvatski",
  " Shona - chiShona",
  " Sindhi",
  " Sinhala - සිංහල",
  "Slovak - slovenčina",
  "Slovenian - slovenščina",
  "Somali - Soomaali",
  "Southern Sotho",
  "Spanish - español",

  "Spanish (Argentina) - español (Argentina)",

  "Spanish (Latin America) - español (Latinoamérica)",

  "Spanish (Mexico) - español (México)",
  " Spanish (Spain) - español (España)",

  " Spanish (United States) - español (Estados Unidos)",

  " Sundanese",
  " Swahili - Kiswahili",
  " Swedish - svenska",
  "Tajik - тоҷикӣ",
  "Tamil - தமிழ",
  " Tatar",
  " Telugu - తెలుగు",
  " Thai - ไทย",
  "Tigrinya - ትግርኛ",
  " Tongan - lea fakatonga",
  "Turkish - Türkçe",
  "Turkmen",
  "Twi",
  "  Ukrainian - українська",
  " Urdu - اردو",
  " Uyghur",
  " Uzbek - o‘zbek",
  "Vietnamese - Tiếng Việt",
  " Walloon - wa",
  " Welsh - Cymraeg",
  "Western Frisian",
  " Xhosa",
  "Yiddish",
  " Yoruba - Èdè Yorùbá",
  "Zulu - isiZulu"
];

export default Language;
